### ISSUE TITLE
Not showing Today's APOD

### ISSUE THREAD

**Issue by iskren-y-g** [TravisL12/apod_chrome_extension#14]
Hi Travis,

first of all, fantastic add-on! Thanks for creating it! I'm using it on Firefox on a Mac. The issue I spotted today is that it doesn't load today's APOD, even if I click on the Today link. It shows the same behavior on Chrome. It just opens a random picture.

My second "request" is about an improvement. It will be good if the Today's APOD is not downloaded every time a new tab is opened, but accessed from the browser cache. This will avoid sometimes (often) slow download, or trigger too many connection requests, if one opens a new tab too often (as I do sometimes).

Cheers,
Iskren

**Comment by TravisL12** [comment]
Thank you so much for the feedback and for using my extension!

Do you by chance know the exact date that wasn’t loading? I’m suspecting
it’s a media type or video that I haven’t planned for and therefore it
doesn’t know how to load it.

As for image caching I originally intended to let the browser cache images
on load and thus after the first load the image will be cached for
subsequent requests. Though I’ll review that this is working as expected.

Thanks again!
Travis Lawrence (The Trav)

**Comment by iskren-y-g** [comment]
The date is today (Dec. 7). It is not showing Today's APOD. It shows me a completely random APOD. Even if I click on Today. I'm not sure if it is a special format, because the picture seems a normal, rather boring one: https://apod.nasa.gov/apod/astropix.html

About the cashing, at least it is not working for me here. It seems that it is downloading it every time ...

Thanks for looking at this! It is a really cool add on and I'd like to see it smoothly working :)

**Comment by TravisL12** [comment]
I looked and it seems the HD image URL is returning a 404 which causes the extension to fallback to just choosing a random date and loading that. Upon further inspection the SD image URL works just fine for today's date (December 7, 2018) and I will put a fix in that will fallback to the SD image if the HD image 404's (or doesn't work for whatever reason).

Thanks again @iskreng !

**Comment by RamiEmad1988** [comment]
Hi Travis, 
Thank you so very much for this amazing extension. I am having the same issue with the Today button and New tab still. It just opens a new tab no matter what I do. And if you would add an option to choose the date it would be perfect!
Thank you so much
