### ISSUE TITLE
Today is giving Random

### ISSUE THREAD

**Issue by RamiEmad1988** [TravisL12/apod_chrome_extension#16]
Hi Travis and thank you so much for this amazing extension,

I have this issue that Today is giving me Random no matter if I switch HD on or off!

This is what I got:
pi.nasa.gov/planetary/apod?api_key=hPgI2kGa1jCxvfXjv6hq6hsYBQawAqvjMaZNs447&date=2019-4-3:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)

Also, I would like to suggest having an option to go to a specific date or a choose for a calendar
And can you change the sun loading animation please? 

thank you a ton

**Comment by TravisL12** [comment]
Thanks so much for the message. Usually when the “today” link isn’t working
it’s because of a failed image resource. But I’ll take a look.

Also I’m tired of the sun loader too. I have a new version coming in
another week or two.

**Comment by TravisL12** [comment]
@RamiEmad1988 just a heads up that I just launched v.2.4 that has a date picker in it. Just click on the date in the title area and the calendar will appear. Let me know what you think!

**Comment by RamiEmad1988** [comment]
Thank you so much for your kind reply. I am trying to download the new
version as it seems my version isn't updated from Chrome Store

**Comment by TravisL12** [comment]
Correction, it is now version 2.4 (not 3.4).
