### ISSUE TITLE
[Feature Request] Make top sites optional

### ISSUE THREAD

**Issue by mrudelle** [TravisL12/apod_chrome_extension#19]
Thanks for you work, I love the extension!

I believe not everybody uses the _top sites_ buttons on a new tab and it would look nicer without them (IMO). 

Would it be possible to make it optional via the settings?

**Comment by TravisL12** [comment]
I'm terribly slow to see these issues. But you raise a good point and making TopSites optional can very easily be accommodated. I'll keep you posted.

**Comment by TravisL12** [comment]
This feature has been added to v3.0.6. Please check the toolbar options menu to see the new checkbox!

![image](https://user-images.githubusercontent.com/2141322/64371114-a46af480-cfd4-11e9-9254-8110c751811a.png)

**Comment by mrudelle** [comment]
Awesome, Thanks for adding that option! 

It's great to see such a nice extension evolving like that ;)
