### ISSUE TITLE
ETag not honoured in Firefox

### ISSUE THREAD

**Issue by shtrom** [TravisL12/apod_chrome_extension#21]
The APoD site has ETags enabled. This can be seen when accessing the site for the first time in the day, with the Developer Tools open on the Network tab, then refreshing.

The first time it will load the image (with an ETag in the response headers), the second time, it will get a 304 and load it, faster, from cache.

When in the extension, however, a refresh never leads to a 304, and the images are always reloaded. This leads to repeat delays, but also additional network use, as a number of images are loaded, and they all are fairly large.

**Comment by TravisL12** [comment]
This is a good insight, I never even thought about it. I'll check my headers and get this sorted out. Thanks!

**Comment by TravisL12** [comment]
What version of Firefox are you using? I was testing this a bit and I was getting a `304` on Today's image. I admit it was a little inconsistent and I also noticed my pre-loading request was firing way too many times (which makes this hard to debug a little).

That being said, I have actually just finished v3.0 of my extension and re-wrote the whole thing in React and using a service worker for caching. It's very fast on Chrome and I'm working towards getting the build ready for Firefox soon. Firefox is a bit more strict on extensions so I'm getting there.

![image](https://user-images.githubusercontent.com/2141322/64389662-713a5c80-cff8-11e9-9a1f-1505698a3958.png)

**Comment by shtrom** [comment]
68.0.2 on OS X. Perhaps Firefox is a bit stricter for privacy reasons?

**Comment by TravisL12** [comment]
I'm on v69.0 (but same difference). Firefox is certainly more strict due to privacy, originally it took me a good refactor to get the extension on the Firefox store.

Anyway, I'm glad you posted a ticket since I didn't really know much about the ETag header and read up on it a bit. Stay tuned for v3 on Firefox in the next week or so.

**Comment by shtrom** [comment]
Cheers. Happy to help test if you need it.
