### ISSUE TITLE
History's scrollbar is visible unnecessarily 

### ISSUE THREAD

**Issue by MagedEWilliam** [TravisL12/apod_chrome_extension#49]
Chrome, windows 10 with dark mode
The scroll is visible breaking the visual constancy

Currently state:
![image](https://user-images.githubusercontent.com/8369718/122103614-1b265a00-ce17-11eb-82b9-ea622ae6738e.png)

expected:
The scrollbar only visible when there are many items

**Comment by TravisL12** [comment]
Please update to the latest version 3.5.5 to have this fixed.
