### ISSUE TITLE
Issue with Save button

### ISSUE THREAD

**Issue by Aman-Anas** [TravisL12/apod_chrome_extension#59]
Using the APOD extension on Firefox 92.0.1 on Windows 10 and have no issues other than this:

When pressing the Save button to favorite an image, it just does nothing. This feature has worked previously, and I have many images still saved in the favorites tab, but I cannot add any more. I can still remove them just fine.

My mouse is over the button, and the button seems clickable (the mouse pointer changes, and the button darkens) but clicking it does nothing:

![image](https://user-images.githubusercontent.com/41600372/136714165-75626d2b-851a-4008-bae9-0bba5f73fba9.png)

**Comment by TravisL12** [comment]
This is fixed.
