### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Pulsar2011** [TravisL12/apod_chrome_extension#79]
Every thing was working fine until recently. Since few days ago,  the I do not have anymore APOD (nore the today pages nor a random page) and the page which is displayed instead is pure white. The debug console of Chrome report the following error message (I hide the API key to avoid making it public)

Failed to load resource: the server responded with a status of 502 () api.nasa.gov/planetary/apod?api_key=<API KEY>&count=10:1

**Comment by TravisL12** [comment]
The NASA API has been down for a few days now. There's really nothing I can do on my end at the moment.

https://github.com/nasa/apod-api/issues/108

**Comment by Pulsar2011** [comment]
Thanks for the précision. I wasn't aware it was the NASA API that was down.
I close the issue

**Comment by TravisL12** [comment]
No problem. It looks like it's up and working again (for now).
